version: 1
metadata:
  name: nokia-srl-grpc
  kind: profile
profile:
  match:
    sysobjectid:
      - 1.3.6.1.4.1.6527.1.20.22 # Nokia SR Linux, type 7220 IXR-D2
    features:
      - gnmi
  reports:
    - nokia-srl-grpc
  include:
    - device_name_ip
  sources:
    - nokia-srl-grpc
